name: example
description: An example project for demonstraction of basic usage of tch_appliable_core.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  flutter_svg: ^1.1.0

  tch_appliable_core:
    path: ../

  path: ^1.8.3

  http: ^1.0.0
  sqflite: ^2.2.8+4

dependency_overrides:
  platform: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/
    - assets/mockUpData/
    - assets/translations/
