name: example
description: An example project for demonstraction of basic usage of tch_appliable_core.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0

  tch_appliable_core:
    path: ../

  path: ^1.9.1

  http: ^1.5.0
  sqflite: ^2.4.2

dependency_overrides:
  # platform: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/
    - assets/mockUpData/
    - assets/translations/
