name: tch_appliable_core
description: Flutter core package used by Tomas Chyly & partners/clients. Contains common functionality to get started faster & consistently.
version: 0.32.3
homepage: https://tomas-chyly.com/en/project/web-browser-detect-flutter/
repository: https://github.com/tomaschyly/tch_appliable_core
issue_tracker: https://github.com/tomaschyly/tch_appliable_core/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  supercharged: ^2.1.1
  flutter_hooks: ^0.20.4

  intl: ^0.19.0
  html_unescape: ^2.0.0
  shared_preferences: ^2.2.2
  path: ^1.8.3
  path_provider: ^2.1.2

  uuid: ^4.3.3
  http: ^1.2.0
  dio: ^5.4.0
  sqflite: ^2.3.0
  sembast: ^3.5.0+1

  pull_to_refresh: ^2.0.0

#dev_dependencies:
  #flutter_test:
    #sdk: flutter

dependency_overrides:
  intl: ^0.19.0

flutter:
