name: tch_appliable_core
description: Flutter core package used by Tomas Chyly & appliable.eu. Contains common functionality to get started faster & consistently.
version: 0.14.0
homepage: https://tomas-chyly.com/en/project/web-browser-detect-flutter/
repository: https://github.com/tomaschyly/tch_appliable_core
issue_tracker: https://github.com/tomaschyly/tch_appliable_core/issues

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  supercharged: ^2.1.1
  flutter_hooks: ^0.18.5+1

  intl: ^0.17.0
  html_unescape: ^2.0.0
  shared_preferences: ^2.0.15
  path: ^1.8.2
  path_provider: ^2.0.11

  http: ^0.13.5
  dio: ^4.0.6
  sqflite: ^2.2.2
  sembast: ^3.3.1

  pull_to_refresh: ^2.0.0

#dev_dependencies:
  #flutter_test:
    #sdk: flutter

flutter:
