name: tch_appliable_core
description: Flutter core package used by Tomas Chyly & partners/clients. Contains common functionality to get started faster & consistently.
version: 0.33.4+1
homepage: https://tomas-chyly.com/en/project/web-browser-detect-flutter/
repository: https://github.com/tomaschyly/tch_appliable_core
issue_tracker: https://github.com/tomaschyly/tch_appliable_core/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  supercharged: ^2.1.1
  flutter_hooks: ^0.20.4

  intl: ^0.19.0
  html_unescape: ^2.0.0
  shared_preferences: ^2.3.2
  path: ^1.8.3
  path_provider: ^2.1.4

  uuid: ^4.5.0
  http: ^1.2.2
  dio: ^5.7.0
  sqflite: ^2.3.3+1
  sembast: ^3.7.4

  pull_to_refresh: ^2.0.0

#dev_dependencies:
  #flutter_test:
    #sdk: flutter

#dependency_overrides:
#  intl: ^0.19.0

flutter:
