name: tch_appliable_core
description: Flutter core package used by Tomas Chyly & partners/clients. Contains common functionality to get started faster & consistently.
version: 0.35.0
homepage: https://tomas-chyly.com/en/project/web-browser-detect-flutter/
repository: https://github.com/tomaschyly/tch_appliable_core
issue_tracker: https://github.com/tomaschyly/tch_appliable_core/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  supercharged: ^2.1.1
  flutter_hooks: ^0.21.3+1

  intl: ^0.20.2
  jiffy: ^6.4.3
  html_unescape: ^2.0.0
  shared_preferences: ^2.5.3
  path: ^1.9.1
  path_provider: ^2.1.5

  uuid: ^4.5.1
  http: ^1.5.0
  dio: ^5.9.0
  sqflite: ^2.4.2
  sembast: ^3.8.5+1

  pull_to_refresh: ^2.0.0

#dev_dependencies:
  #flutter_test:
    #sdk: flutter

#dependency_overrides:
#  intl: ^0.19.0

flutter:
