name: tch_appliable_core
description: Flutter core package used by Tomas Chyly & appliable.eu. Contains common functionality to get started faster & consistently.
version: 0.24.3
homepage: https://tomas-chyly.com/en/project/web-browser-detect-flutter/
repository: https://github.com/tomaschyly/tch_appliable_core
issue_tracker: https://github.com/tomaschyly/tch_appliable_core/issues

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  supercharged: ^2.1.1
  flutter_hooks: ^0.18.6

  intl: any #^0.18.0
  html_unescape: ^2.0.0
  shared_preferences: ^2.1.2
  path: ^1.8.3
  path_provider: ^2.0.15

  http: ^1.0.0
  dio: ^5.2.1+1
  sqflite: ^2.2.8+4
  sembast: ^3.4.7

  pull_to_refresh: ^2.0.0

#dev_dependencies:
  #flutter_test:
    #sdk: flutter

# dependency_overrides:
#   intl: ^0.18.0

flutter:
